void menu();
int pintartabuleiro();
void jogar();
int moverpeca(int linha_origem, int linha_destino, int coluna_origem, int coluna_destino);
void white_wins();
void black_wins();
void copy();
void verificar_op_menu(int* op);
void verificar_op_copy(int* op);
void verificar_lin_ori(int* linha_origem);
void verificar_col_ori(int* coluna_origem);
void verificar_lin_des(int* linha_destino);
void verificar_col_des(int* coluna_destino);